# Generated by Django 6.0.2 on 2026-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studenttestrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestrecords',
            name='total_tests_conducted',
        ),
        migrations.AddField(
            model_name='student',
            name='total_tests_conducted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
