# Generated by Django 6.0.2 on 2026-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='default_notification_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10, null=True),
        ),
    ]
